server: 
  port: 8081
  servlet: 
    context-path: /jwt-resource-server
logging:
  level:
    root: DEBUG
####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.101:8890/auth/realms/baeldung
          jwk-set-uri: http://192.168.0.101:8890/auth/realms/baeldung/protocol/openid-connect/certs